// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdeJgYGxyEDwqXGrR37iVWHMkhPssHklE',
    appId: '1:858947528406:web:4d35b43f8c4cf9e4f60b77',
    messagingSenderId: '858947528406',
    projectId: 'sourajit-4475a',
    authDomain: 'sourajit-4475a.firebaseapp.com',
    storageBucket: 'sourajit-4475a.appspot.com',
    measurementId: 'G-W5B0J9K1TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQJubu8LFuSLknOWx0NXSEHNBNg6YyBmk',
    appId: '1:858947528406:android:f7cd3be90b68cb3ef60b77',
    messagingSenderId: '858947528406',
    projectId: 'sourajit-4475a',
    storageBucket: 'sourajit-4475a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWhWjKSO-p_drNhx2wvZLC3LZk-PVzHJA',
    appId: '1:858947528406:ios:2d1371268e2b3a14f60b77',
    messagingSenderId: '858947528406',
    projectId: 'sourajit-4475a',
    storageBucket: 'sourajit-4475a.appspot.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWhWjKSO-p_drNhx2wvZLC3LZk-PVzHJA',
    appId: '1:858947528406:ios:2d1371268e2b3a14f60b77',
    messagingSenderId: '858947528406',
    projectId: 'sourajit-4475a',
    storageBucket: 'sourajit-4475a.appspot.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );
}
